### ISSUE TITLE
possibility to disable 2 factor authentication

### ISSUE THREAD

**Issue by streamcoindev** [scatterp/peatio_princeberk#11]
Is it there? this is for testing purposes

**Comment by scatterp** [comment]
i think its already disabled please double check
controllers/application_controller.rb:  def is_admin?

**Comment by lanaiscool** [comment]
def is_admin?
    current_user && current_user.admin?
  end

i need google authenticator to access funds, withdrawal and admin panel

**Comment by scatterp** [comment]
yeah that looks like it

**Comment by scatterp** [comment]
did it work ?

**Comment by lanaiscool** [comment]
Its enabled still for admins and normal users
