### ISSUE TITLE
Can you add this commit ?

### ISSUE THREAD

**Issue by streamcoindev** [scatterp/peatio_princeberk#13]
https://github.com/peatio/peatio/pull/568/commits/7bc50de2caa53254769a758e91f6878e9ecb353d

**Comment by scatterp** [comment]
submit a pull request to scatterp4/peatio
will test it if it works good then yes

**Comment by lanaiscool** [comment]
wallet generation is working am testing deposit and withdrawal now

**Comment by scatterp** [comment]
ok how did it go ?
