### ISSUE TITLE
cant login to admin on new install

### ISSUE THREAD

**Issue by outbackdingo** [scatterp/peatio_princeberk#19]
user: admin@peatio.dev
pass: Pass@word8

not working to login on new install

The network connection is temporarily unavailable... Please refresh.

**Comment by scatterp** [comment]
ok please leave a skype address i will contact you directly

**Comment by outbackdingo** [comment]
digismurf@live.com

**Comment by outbackdingo** [comment]
done digismurf@live.com is my skype

**Comment by outbackdingo** [comment]
ok still cant login as admin@peatio.dev  with password i can login as a user however

**Comment by scatterp** [comment]
you can create an account with admin@peatio.dev as an email address and then login

**Comment by outbackdingo** [comment]
ok added  the user admin@peatio.dev

its asking  now to set a mobiles number but dont see anywhere in the profile
and authenticator keeps saying  wrong password ?
Two-Factor Authentication
Two-Factor Authentication
Iphone iOS
Android
￼×
Password for authentication is incorrect, please re-enter pass.


Please set mobile number or google authenticator first.
￼×
An email has been sent to your mailbox, please check it for verification as
soon as possible. If you do not received it , please click "send it again"
button

**Comment by scatterp** [comment]
for authenticator ensure the time on your phone is set correctly and the time is set correctly by the supplier of your vps 
to set a number you can do this with mysql from the database i have it disabled currently (will re-enable it in a later commit)

**Comment by pkdcryptos** [comment]
Hi scatterp
Thanks for your work. Is there any demo website running for this code ? I am just getting bear ubuntu VPS to try this out and try single install ie install1.sh. Is there any service we can get from you to install exchange on local ubuntu server ? I can help changing all to php and gave it back to you. But i need to have running site to chnage all the code to php though. Thanks for your help in advance,
Kumar

**Comment by pkdcryptos** [comment]
My skype id: pkdcryptos@gmail.com / Pkd Cryptos
Thanks
