### ISSUE TITLE
Can't Run bundle exec rake db:setup

### ISSUE THREAD

**Issue by prateekdarmwal1** [scatterp/peatio_princeberk#28]
I need help with setting up databse. I am trying to setup database but can't run 
`bundle exec rake db:setup`

I am getting below error: 

`bundle exec rake db:setup --trace
W, [2017-12-29T19:06:09.929677 #7586]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /home/neeraj/.rvm/gems/ruby-2.3.4/gems/omniauth-1.2.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /home/neeraj/Documents/rails/peatio/config/application.rb:12)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 65910 was converted to "65910". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
** Invoke environment (first_time)
** Execute environment
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'peatio_development.documents' doesn't exist: SHOW FULL FIELDS FROM `documents`
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `query'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:324:in `execute_and_free'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:471:in `columns'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/attributes.rb:93:in `columns'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/attribute_methods/serialization.rb:62:in `serialized_attributes'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:53:in `enable_serializable_attribute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:31:in `block in allow_translation_of_attributes'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:29:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:29:in `allow_translation_of_attributes'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:12:in `translates'
/home/neeraj/Documents/rails/peatio/app/models/document.rb:3:in `<class:Document>'
/home/neeraj/Documents/rails/peatio/app/models/document.rb:1:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `block in load_file'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:647:in `new_constants_in'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:456:in `load_file'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:354:in `require_or_load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:317:in `depend_on'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:233:in `require_dependency'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:471:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:471:in `block in eager_load!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:469:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:469:in `eager_load!'
/home/neeraj/Documents/rails/peatio/config/routes.rb:1:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/file_update_checker.rb:75:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
/home/neeraj/Documents/rails/peatio/config/environment.rb:6:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:251:in `block in execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:251:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:251:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:181:in `invoke'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:160:in `invoke_task'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:116:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:116:in `block in top_level'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:125:in `run_with_threads'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:110:in `top_level'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:83:in `block in run'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/rake:22:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/rake:22:in `<main>'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Mysql2::Error: Table 'peatio_development.documents' doesn't exist
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `query'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:324:in `execute_and_free'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:471:in `columns'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/attributes.rb:93:in `columns'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/attribute_methods/serialization.rb:62:in `serialized_attributes'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:53:in `enable_serializable_attribute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:31:in `block in allow_translation_of_attributes'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:29:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:29:in `allow_translation_of_attributes'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:12:in `translates'
/home/neeraj/Documents/rails/peatio/app/models/document.rb:3:in `<class:Document>'
/home/neeraj/Documents/rails/peatio/app/models/document.rb:1:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `block in load_file'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:647:in `new_constants_in'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:456:in `load_file'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:354:in `require_or_load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:317:in `depend_on'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:233:in `require_dependency'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:471:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:471:in `block in eager_load!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:469:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:469:in `eager_load!'
/home/neeraj/Documents/rails/peatio/config/routes.rb:1:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/file_update_checker.rb:75:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
/home/neeraj/Documents/rails/peatio/config/environment.rb:6:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:251:in `block in execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:251:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:251:in `execute'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:215:in `invoke_prerequisites'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/task.rb:181:in `invoke'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:160:in `invoke_task'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:116:in `each'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:116:in `block in top_level'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:125:in `run_with_threads'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:110:in `top_level'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:83:in `block in run'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
/home/neeraj/.rvm/gems/ruby-2.3.4/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/rake:22:in `load'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/rake:22:in `<main>'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/home/neeraj/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
`
Anyone have this issue before?
Please help thanks

**Comment by prateekdarmwal1** [comment]
Got a workaround. Create documents table manually from this sql file.

`--
-- Table structure for table `documents`
--

CREATE TABLE `documents` (
  `id` int(11) NOT NULL,
  `key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8_unicode_ci,
  `is_auth` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `desc` text COLLATE utf8_unicode_ci,
  `keywords` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `documents`
--
ALTER TABLE `documents`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `documents`
--
ALTER TABLE `documents`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;`

Then ran `bundle exec rake db:setup` and it worked. But still need to check why this error was invoked.

**Comment by NFhbar** [comment]
I have the same issue but cannot solve it.
