### ISSUE TITLE
Need someone to Install, configure and customize Peatio. 

### ISSUE THREAD

**Issue by prashantdhamija** [scatterp/peatio_princeberk#29]
Hi folks!

I'm looking for someone for installation/customization and configuration of Peatio.

Please reach out to me on my Skype: Prashantdhamija3@gmail.com or email me at prashantdhamija3@gmail.com

Thanks!

**Comment by prashantdhamija** [comment]
Edit: Skype is Prashantdhamija3

**Comment by mxo2** [comment]
contact sam@mxo2.com for installation peatio
