### ISSUE TITLE
Market Dashboard Blank. Am i missing something ? 

### ISSUE THREAD

**Issue by satheshhmax** [scatterp/peatio_princeberk#30]
Hi,

After following all the steps provided in https://github.com/scatterp/peatio/blob/master/doc/setup-local-ubuntu.md i got the application up and running. 

But i am not sure if i am missing anything to populate the market data in my local. Say in the URL http://localhost:3000/markets/btccny

Someone please point me out with what i am missing. Refer below image.
 
![download](https://user-images.githubusercontent.com/120826/34654144-497df6ba-f41d-11e7-97e5-43faa716636f.png)

**Comment by scatterp** [comment]
nope there was never any trades so of course its blank add me on skype if you need help with liquidity provision and feeds the solution for this simon.m.day
