### ISSUE TITLE
Error doing precompile

### ISSUE THREAD

**Issue by eric-tsoi** [scatterp/peatio_princeberk#33]
Tried many different Ruby versions 2.2.2, 2.2.9, 2.4.3 and 2.5.0. All got precompile failed with the folllowing errors.

**#bundle exec rake assets:precompile**

1. Sass::SyntaxError: Undefined mixin 'transform'.
/home/deploy/peatio/scatterp/app/assets/stylesheets/market.css.scss:265:in `transform'

Commented out the transform calls in the market.css.scss and then got the following missing file error.

2. Sprockets::FileNotFound: couldn't find file 'bootstrap-wysihtml5/b3' with type 'application/javascript'
Checked in these paths: 
  /home/deploy/peatio/scatterp/app/assets/images
  /home/deploy/peatio/scatterp/app/assets/javascripts

Please kindly advise.

**Comment by jawb** [comment]
For 2nd issue, in GemFile force version:
gem 'bootstrap-wysihtml5-rails', '0.3.1.24'

**Comment by scatterp** [comment]
@jawb , did you manage to run Peatio flawlessly? Add me on skype if you have any assistance: martin_princeberk
