### ISSUE TITLE
I feel close, but something is wrong. 

### ISSUE THREAD

**Issue by Simplexletalis** [scatterp/peatio_princeberk#34]
peatio/spec/factories/payment_addresses.rb:11:in `block (3 levels) in <top (required)>': undefined method `id' for nil:NilClass (NoMethodError)
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/trait.rb:12:in `instance_eval'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/trait.rb:12:in `initialize'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/definition_proxy.rb:161:in `new'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/definition_proxy.rb:161:in `trait'
        from /root/daemon/bitcoin/bin/peatio/spec/factories/payment_addresses.rb:8:in `block (2 levels) in <top (required)>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:18:in `factory'
        from /root/daemon/bitcoin/bin/peatio/spec/factories/payment_addresses.rb:4:in `block in <top (required)>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:49:in `run'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:7:in `define'
        from /root/daemon/bitcoin/bin/peatio/spec/factories/payment_addresses.rb:3:in `<top (required)>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `block in load'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:19:in `each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:15:in `each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl_rails-4.3.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /root/daemon/bitcoin/bin/peatio/config/environment.rb:5:in `<top (required)>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
        from /root/daemon/bitcoin/bin/peatio/config.ru:3:in `block in <main>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from /root/daemon/bitcoin/bin/peatio/config.ru:in `new'
        from /root/daemon/bitcoin/bin/peatio/config.ru:in `<main>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/commands/server.rb:48:in `app'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/commands/server.rb:75:in `start'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/commands.rb:76:in `block in <top (required)>'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/commands.rb:71:in `tap'
        from /root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/commands.rb:71:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by cph-at129** [comment]
i dont fully follow what happened here as there is no history of how you got to this point but please add simon.m.day (scatterp) and we will try to help you
