### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by wozzi** [scatterp/peatio_princeberk#37]
Hi,

Been trying to setup for a while now to fiddle around, and finding it hard to find any forks that give a basic working platform. When I saw the install1.sh I was so happy, but ran it and still doesn't seem to work. Is there anything else to it?
I installed 16.04 ubuntu server. clone the rep, then ran install1.sh. Put in the details when asked. At end I can't seem to get to localhost:3000

Any insight would be appreciated.

Thanks

**Comment by jiyocoin** [comment]
???

**Comment by wozzi** [comment]
![p](https://user-images.githubusercontent.com/37660343/38612479-1c009112-3d87-11e8-9915-8349ee18a1de.jpg)

**Comment by no-dev** [comment]
Hi,

I was playing with it yesterday too and had same result as OP.

Fresh Ubuntu server 16.04.4 minimal install (Hyper-V VM, haven't tried on other platforms yet), installed wget, downloaded the script, sourced the script, put details when it asked for, all completed automatically with no errors.  No firewalls, iptables is accepting everything but when trying to browse to the server on port 3000 nothing comes up.

As wozzi said any insight will be appreciated.

Many Thanks

**Comment by no-dev** [comment]
Hi jiyocoin,

What's the relation between the issue raised and JIYO MN? How is that supposed to help?



Thanks

**Comment by scatterp** [comment]
@no-dev Have you been able to run it? Can you try installing fresh without port 3000 ? Let me know if you experience any issues further - Skype: martin_princeberk
