### ISSUE TITLE
add monero and cryptonote

### ISSUE THREAD

**Issue by IB313184** [scatterp/peatio_princeberk#38]
buenas. he incrementado varias monedas ltc, dash, doge, zec, btc.
estoy intentando añadir a monero y algunas cryptonote, no soy capaz y creo que tengo todo la incrementacion bien.
me podrían decir con detalles la parte de los demonios como a de ser o alguna guia a seguir.

gracias.

good. I have increased several currencies ltc, dash, doge, zec, btc.
I'm trying to add monero and some cryptonote, I'm not capable and I think I have all the increase well.
They could tell me in detail the part of the demons as to be or some guide to follow.
Thank you.

**Comment by minersbad** [comment]
Hola Ernico, contact my please minersbad@gmail.com

**Comment by scatterp** [comment]
@IB313184 Have you managed to add the coins in terms of instruments or you actually made them sync with Peatio? Add me on skype if you experience some issues: martin_princeberk
