### ISSUE TITLE
Paid job - VPS installation

### ISSUE THREAD

**Issue by appsdev9** [scatterp/peatio_princeberk#39]
Deleted.

**Comment by minersbad** [comment]
https://peatio.io

**Comment by scatterp** [comment]
@appsdev9 did you manage to bring it up?

**Comment by M3rc4nt3** [comment]
ciao can you help in an installation? cheers

**Comment by appsdev9** [comment]
You want to hire someone?

2018-07-22 8:06 GMT+08:00 M3rc4nt3 <notifications@github.com>:

**Comment by M3rc4nt3** [comment]
yes

**Comment by appsdev9** [comment]
Installation is OK, but the maintenance / customization is quite tough for
a non-technical guy?

Do you have any tech knowledge?

2018-07-22 21:53 GMT+08:00 M3rc4nt3 <notifications@github.com>:

**Comment by M3rc4nt3** [comment]
hmmm last year i almost installed it. need help

**Comment by M3rc4nt3** [comment]
can u help?

**Comment by appsdev9** [comment]
What is your budget in US$?

2018-07-23 2:38 GMT+08:00 M3rc4nt3 <notifications@github.com>:

**Comment by M3rc4nt3** [comment]
Low budget from the beginning, but there is room for a maintainance contract. How much would you charge for full install with erc20 support etc. and monthly maintainance on our servers.

**Comment by appsdev9** [comment]
Sorry that I am quite busy recently and could not help. Cheers.

2018-07-24 7:06 GMT+08:00 M3rc4nt3 <notifications@github.com>:
