### ISSUE TITLE
mismatch Gemfile and Gemfile.lock

### ISSUE THREAD

**Issue by jod033116** [scatterp/peatio_princeberk#40]
user@ubuntu:~/peatio/current$ bundle install

The git source `git://github.com/scatterp/unread.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/scatterp/mina-slack.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/scatterp/mina-slack.git

Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
You have requested:
  omniauth ~> 1.2.2

The bundle currently has omniauth locked at 1.8.1.
Try running `bundle update omniauth`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
user@ubuntu:~/peatio/current$

**Comment by scatterp** [comment]
@jod033116 have you by any chance done an update on the system before you begun? Add me on skype if you experience more problems: martin_princeberk
