### ISSUE TITLE
bundle exec rake db:setup => produces error

### ISSUE THREAD

**Issue by crown111** [scatterp/peatio_princeberk#41]
I have added my database permissions to the ./config/database.yml but I am getting the following error every time. I have tried running the command from sudo as well. Thx

ub:/usr/local/share/code/peatio$ bundle exec rake db:setup --trace
rake aborted!
NoMethodError: undefined method `yield_self' for false:FalseClass
/usr/local/share/code/peatio/config/plugins.rb:1:in `<top (required)>'
/usr/local/share/code/peatio/config/application.rb:12:in `require_relative'
/usr/local/share/code/peatio/config/application.rb:12:in `<top (required)>'
/usr/local/share/code/peatio/Rakefile:5:in `require'
/usr/local/share/code/peatio/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:82:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

**Comment by lishengpeng** [comment]
source install1.sh

**Comment by scatterp** [comment]
@crown111 have you installed on a clean Ubuntu 16.04 distribution at a normal physical server or was it a cloud service somewhere like AWS ? Try using a separate user with sudo privileges with the command as @lishengpeng has shown above and if you experience more problems, you can add me on skype: martin_princeberk as I'm not that active here
