### ISSUE TITLE
Production version won't build

### ISSUE THREAD

**Issue by Illuzion-maker** [scatterp/peatio_princeberk#45]
After running 

`bundle install --without development test --path vendor/bundle`
i'm getting this:
`git://github.com/peatio/unread.git fatal: remote error: Repository not found.`

**Comment by scatterp** [comment]
@Illuzion-maker , can you specify all environmental details such as a server configuration, software configuration and all possible details to explain a bit more about how did you come up to this?

**Comment by Illuzion-maker** [comment]
Well it's 2xXeon 96Gb RAM server. Ubuntu 16 latest one. Your gem file trying to get 2 repos which is not exist in peatio git anymore (I mean that Gemfile which is your repo), i was done as in deploy production README
looks like some thing went wron here, cause it tryed to download it from old peatio repo. Now i'm looking and there is normal path.
Cloned it again, made bundle install for production. Getted this:
```
You have requested:
  omniauth ~> 1.2.2

The bundle currently has omniauth locked at 1.8.1.
Try running `bundle update omniauth`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
```

updated omniauth with `bundle update omniauth`

then done 
`bundle install --without development test --path vendor/bundle`

And get no errors

then 
`bin/init_config`
entered all data to config files

`bundle exec rake db:setup`
done next


get this 
`Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).`

was checked Gem file - its here and added

**Comment by Illuzion-maker** [comment]
I"ve found this in Gemfile.lock
```
 omniauth (1.8.1)
      hashie (>= 3.4.6, < 3.6.0)
rack (>= 1.6.2, < 3)
```

and this in usual Gemfile:

```
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-identity', '~> 1.1.1'
gem 'omniauth-weibo-oauth2', '~> 0.4.0'
```

But have no idea how to fix it,

**Comment by scatterp** [comment]
Not a big issue, will post a fix lately, just completely overloaded lately with projects.
