### ISSUE TITLE
Production server not running

### ISSUE THREAD

**Issue by susmit** [scatterp/peatio_princeberk#46]
I followed two step installation on server (ubuntu 16.04).I am unable to access the server at ip after
 `sudo bundle exec rails server`
and throwing me the folloeing error.
```
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
bundler: command not found: rails
Install missing gem executables with `bundle install`

```

**Comment by scatterp** [comment]
Can you specify all environmental details including steps of how did you get up to here?
